### PR TITLE
Add basic experimental GUI

### PR DESCRIPTION
**Pull request by ZedThree**
Basic but useful interface to the options. Features:

- Creates a table dynamically from the `TokamakEquilibrium.default_options` or a loaded yaml file
- Add new options
- Fuzzy search options + autocomplete
- Save set options to file
- Plots loaded geqdsk file according to current options (changing an options reloads the file and replots)
- Create a `BoutMesh` and save to file

hypnotoad2_screenshot2

Current downsides:

- Very noisy in terminal
    - need to add `quiet/verbose` flags to hypnotoad2 functions
- Running hypnotoad2 is blocking
    - add threading
- Comments are not preserved when loading/saving yaml file
    - switch to `ruamel.yaml`?
- Only handles geqdsk/tokamak equilibrium, not torpex
    - add choice/switch somehow?
    - ability to register different equilibria?

Future features?

- Plot other things
- Integrate FreeGS/xBOUT?
- Prototyping on reduced grid?
- Documentation for options?

### CODE REVIEW

**Comment by bendudson** [comment]
Sweet!  Thanks @ZedThree this looks great!

**Comment by ZedThree** [comment]
I `black`-formatted `hypnotoad2_mainWindow.py`, even though this is auto-generated from `hypnotoad2_mainWindow.ui` by `pyside2-uic`, as the path of least resistance. Turns out `black` uses `pyproject.toml` as its config file, and this may have repercussions on how pip builds the project.

`pyproject.toml` does appear to be "the future", but I've not investigated it fully enough yet.

---

There's a plugin for pytest to test Qt apps. Might be worth looking in to when I have more time.

---

I have this vague idea of how a workflow with this tool would work. The window would have three tabs; the first to load or generate an equilibrium, either loading from a file, generated by FreeGS, or an analytic one like torpex or how Zoidberg works; a second tab to construct the mesh, this could even have an option to generated Zoidberg grids; and the last tab to load and plot simulation results.

**Comment by johnomotani** [comment]
`pyproject.toml` has tool-specific sections. Adding one with just a `[tool.black]` section doesn't seem to upset pip, so I think that's probably the way to go. I can revert the formatting and add a `pyproject.toml` - I'm just going to test out the gui to check that the `pip install -e .` actually worked properly.

**Comment by ZedThree** [comment]
Thanks @johnomotani ! Only recalculating R, Z made it much zippier for me!

Getting a coarse prototyping grid in and recalculating that mesh whenever options change might be plausible.

**Pull request merged**
